---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: smartos-base64
  driver_config:
    box: livinginthepast/smartos-base64
    vagrantfile_erb: test/templates/Vagrantfile.smartos.erb
  provisioner:
    name: chef_zero
    sudo: true
    chef_omnibus_url: https://raw.github.com/wanelo-chef/chef-bootstrap/master/latest.sh
    # chef_omnibus_url: https://raw.github.com/test-kitchen/kitchen-joyent/master/scripts/install-smartos.sh

suites:
- name: default
  run_list:
    - recipe[nginx::default]
- name: package
  run_list:
    - recipe[test_nginx_site::package]
- name: source
  run_list:
    - recipe[test_nginx_site::source]
- name: site_enable
  run_list:
    - recipe[test_nginx_site::enable]
- name: site_disable
  run_list:
    - recipe[test_nginx_site::disable]
- name: update_from_package_to_source
  run_list:
    - recipe[test_nginx_site::update_from_package_to_source]
  attributes: { nginx: { service: { name: 'pkgsrc/nginx'}}}
